servers:
  - type: sqlserver
    label: SQL Server
    instances:
      - name: PROD-SQL-01
        host: localhost
        port: 1433
        user: sa
        password: YourStrongPassword123!
        options:
          encrypt: false
          trustServerCertificate: true
      - name: DEV-SQL-01
        host: localhost
        port: 1433
        user: sa
        password: YourStrongPassword123!
        options:
          encrypt: false
          trustServerCertificate: true
  - type: postgres
    label: PostgreSQL
    instances:
      - name: pg-cluster-prod
        host: localhost
        port: 5432
        user: postgres
        password: YourStrongPassword123!
