servers:
  - type: sqlserver
    label: SQL Server
    instances:
      - name: PROD-SQL-01
        host: localhost
        port: 1433
        user: sa
      - name: DEV-SQL-01
        host: localhost
        port: 1433
        user: sa
  - type: postgres
    label: PostgreSQL
    instances:
      - name: pg-cluster-prod
        host: localhost
        port: 5432
        user: postgres
